# Generated by Django 5.0.7 on 2024-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_leader_add_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_leader',
            name='job_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
