# Generated by Django 5.0.7 on 2024-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_add_leader_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_member',
            name='job_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
