# Generated by Django 5.0.7 on 2024-08-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_assign_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_member',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
