# Generated by Django 5.0.7 on 2024-08-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_member_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_member',
            old_name='status',
            new_name='assigned_status',
        ),
    ]
