# Generated by Django 5.0.7 on 2024-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_assign_work_completed_assign_work_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_work',
            name='progress',
            field=models.IntegerField(default=60),
        ),
    ]
