# Generated by Django 5.0.7 on 2024-08-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_assign_work_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_work',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
