# Generated by Django 5.0.7 on 2024-08-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_assign_work_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_work',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='assign_work',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='assign_work',
            name='progress',
        ),
        migrations.AddField(
            model_name='add_project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add_project',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='add_project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
