# Generated by Django 5.0.7 on 2024-08-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Add_comment',
        ),
    ]
