# Generated by Django 5.0.7 on 2024-08-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_comment_add_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_comment',
            name='project_id',
        ),
        migrations.AddField(
            model_name='add_comment',
            name='work_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.assign_work'),
        ),
    ]
