# Generated by Django 5.0.7 on 2024-08-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_add_comment_project_id_add_comment_work_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_comment',
            new_name='Add_comments',
        ),
    ]
