# Generated by Django 5.0.7 on 2024-08-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_add_comment_add_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_comments',
            name='member_id',
        ),
    ]
