# Generated by Django 5.0.7 on 2024-08-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_comments_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_comments',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.add_project'),
        ),
    ]
