# Generated by Django 5.0.7 on 2024-08-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_add_comments_project_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_comments',
            new_name='Add_comment',
        ),
    ]
