# Generated by Django 5.0.7 on 2024-08-29 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_add_comments_add_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_comment',
            name='work_id',
        ),
        migrations.AddField(
            model_name='add_project',
            name='fifth_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_fifth_member', to='myapp.add_member'),
        ),
        migrations.AddField(
            model_name='add_project',
            name='first_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_first_member', to='myapp.add_member'),
        ),
        migrations.AddField(
            model_name='add_project',
            name='fourth_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_fourth_member', to='myapp.add_member'),
        ),
        migrations.AddField(
            model_name='add_project',
            name='second_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_second_member', to='myapp.add_member'),
        ),
        migrations.AddField(
            model_name='add_project',
            name='third_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_third_member', to='myapp.add_member'),
        ),
        migrations.DeleteModel(
            name='Assign_work',
        ),
    ]
