# Generated by Django 5.0.7 on 2024-08-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_add_comment_work_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_member',
            name='assigned_status',
        ),
    ]
