# Generated by Django 5.0.7 on 2024-08-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_add_member_assigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_member',
            name='assigned_status',
            field=models.BooleanField(default=False),
        ),
    ]
