# Generated by Django 5.0.7 on 2024-08-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_add_member_assigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_project',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='add_project',
            name='project_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
