# Generated by Django 5.0.7 on 2024-08-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_add_project_assigned_add_project_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_member',
            name='assigned_status',
        ),
    ]
