# Generated by Django 5.0.7 on 2024-08-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_add_member_assigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_project',
            name='admin_approvel',
            field=models.BooleanField(default=False),
        ),
    ]
