# Generated by Django 5.0.7 on 2024-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_add_project_admin_approvel'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_project',
            name='admin_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
