# Generated by Django 5.0.7 on 2024-08-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_add_project_admin_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_project',
            old_name='admin_approvel',
            new_name='leader_approvel',
        ),
        migrations.RenameField(
            model_name='add_project',
            old_name='admin_rejected',
            new_name='leader_rejected',
        ),
    ]
